version: "3"

services:
  web:
    image: php:8.0-apache
    networks:
      - default
    container_name: web_5
    volumes:
      - ./src:/var/www/html:ro
    # ports:
    #   - "8005:80"
    env_file:
      - .env

networks:
  default:
    external:
      name: web5_internal
