"""empty message

Revision ID: 888d777972ff
Revises: 4d3c1b59d011
Create Date: 2022-05-03 07:51:58.078761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888d777972ff'
down_revision = '4d3c1b59d011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('challenge_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'awards', 'challenges', ['challenge_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'awards', type_='foreignkey')
    op.drop_column('awards', 'challenge_id')
    # ### end Alembic commands ###
