version: "3"

services:
  web:
    image: web2:lamp
    build: .
    networks:
      - default
    container_name: web_2
    volumes:
      - ./src:/app:ro
      - mysql_data:/var/lib/mysql
      - php_data:/var/www
    # ports:
    #   - "8002:80"
    env_file:
      - .env

volumes:
  mysql_data:
  php_data:

networks:
  default:
    external:
      name: web2_internal
